---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podscalers.puzzle.ch
spec:
  scope: Cluster
  group: puzzle.ch
  names:
    kind: PodScaler
    plural: podscalers
    singular: podscaler
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                status:
                  type: string
                filter:
                  type: string
                no_daemonset:
                  type: boolean
