apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podscalers.puzzle.ch
spec:
  scope: Cluster
  group: puzzle.ch
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: PodScaler
    plural: podscalers
    singular: podscaler
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            namespace:
              type: string
            status:
              type: string
            filter:
              type: string
            no_daemonset:
              type: boolean
